### ISSUE TITLE
Target groups in Introduction

### ISSUE THREAD

**Issue by rallek** [Guite/MostHelp#10]
There is no information which skills are needed to use MOST

**Comment by Guite** [comment]
The first paragraph contains: _Software developers can create complex Zikula extensions in a few steps and meet individual project requirements with them._

Do you think a separate section *target audience* is required? At the end there is a wide range from end users without any development experience to professional agencies...

**Comment by rallek** [comment]
As you can see how easy to overread this a list of minimum requirements might be helpfull and will reduce the frustration if the modul is not doing what you expect.

Something like:
* basic knowledge in css
* basic knowledge in html
* able to read php code
* for implemention business logic or function you should be able to code in php

advanced user recommended
* symfony
* doctrine

...
