### ISSUE TITLE
Add new chapter about "generator topics"

### ISSUE THREAD

**Issue by Guite** [Guite/MostHelp#20]
The generator reference chapter is a comprehensive collection of all DSL properties and their effects in the generated code. But it does not help with getting an overview of _how to get done_ something specific.
Thus, it would be helpful to have another dedicated chapter which describes several topics:

- Models (everything relating the Doctrine mappings)
- View pages (relevant settings, other possibilities)
- Edit forms (different input field types, relationships, special additions)
- Extensions (Doctrine extensions, other behavioural settings, e.g. different and enhanced permalinks)
- Permissions (filtering, inheritance by relationships, category permissions)
- Workflows (ownerPermission, approvals, moderation capabilities, etc.)
- Hooks
- Integrations
- ...

**Comment by rallek** [comment]
I would like another approach. 
At what place do you need the help? Mainly during editing the model in Modulestudio. There you have the ``?`` with a tooltip.
![grafik](https://user-images.githubusercontent.com/935250/32699500-287161ce-c7b7-11e7-8b96-bd4083f0af84.png)
Make this tooltip a link to a website with the cross reference for all these small helping things. This website could be similar to a reference of a syntax website e.g. https://twig.symfony.com/doc/2.x/functions/max.html
E.G. on the top of such a property view or other interesting places of MOST you can add another ``?`` for more generic explanation.

If this reference site is a zikula module you can manage also translations for this.
